### PR TITLE
fix: use othent sign and send functions

### PR DESCRIPTION
**Pull request by 7i7o**

### CODE REVIEW

**Comment by 7i7o** [comment]
Hey @pawanpaudel93 , I moved as little code as possible to use the sign and send functions from othent. Now the data is being saved to arweave
How can we check the contents of the databuffer before signing and sending?

**Comment by pawanpaudel93** [comment]
@7i7o othent package has issue with this line https://github.com/Othent/package/blob/d004e5ce6ffe15f4c116a4fac2ddfe60d18e58e9/src/lib/index.ts#L421 as we are sending ArrayBuffer to the signing function and othent package is converting to string first and it does not work. So I have added a pull request to othent https://github.com/Othent/package/pull/19

**Comment by 7i7o** [comment]
@pawanpaudel93 Already merged your PR in Othent. You can now update Permatok to use the new version with the sing and send functions to solve this issue 😊

**Comment by pawanpaudel93** [comment]
@7i7o, Thank you for the merge and PR as well. I will update othent.

**Pull request merged**
